/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/bamigos2.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model3(props) {
  const { nodes, materials } = useGLTF('./models/bamigos2.gltf')
  return (
    <group {...props} dispose={null} rotation={[0, -Math.PI / 2, 0]}>
      <mesh geometry={nodes.M2_mainBody.geometry} material={materials.M2_MainBody_Mat} />
      <group position={[0.099, 0.887, 0.213]} rotation={[-0.066, 0, 0]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials.M_Action_btn_Frane} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.M_Action_btn_} />
      </group>
      <group position={[-0.125, 0.887, 0.213]} rotation={[-0.066, 0, 0]}>
        <mesh geometry={nodes.Circle002.geometry} material={materials.M_Action_btn_Frane} />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.M_Action_btn_} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/bamigos2.gltf')
