/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/vendor/models/bamigos.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/bamigos1.gltf')
  return (

    <group {...props} dispose={null} >
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={10} visible={false}/>
      <group position={[0, 0, 0.051]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.ControlPanel.geometry} material={materials['Material.001']} position={[0, 0, 0.051]} />
      <group position={[-0.002, 0.836, 0.263]}>
        <mesh geometry={nodes.Circle.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/bamigos1.gltf')
