/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/bamigos3.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model3(props) {
  const { nodes, materials } = useGLTF('./models/bamigos3.gltf')
  return (
    <group {...props} dispose={null} rotation={[0, Math.PI / 4, 0]}>
      <mesh geometry={nodes.M3_MainBody.geometry} material={materials.Material_M3_Tex} />
      <mesh geometry={nodes.M3_FrontPanel.geometry} material={materials.Material_M3_Tex} position={[0, 0, -0.012]} />
      <mesh geometry={nodes.M3_Speaker.geometry} material={materials.Material_M3_Tex} />
      <mesh geometry={nodes.M3_Scren.geometry} material={materials.Material_M3_Tex} />
    </group>
  )
}

useGLTF.preload('./models/bamigos3.gltf')
